arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

c_stdlib_version:  # [linux]
   - "2.28"        # [linux]

c_compiler_version:    # [linux]
  - 14.3.0             # [linux]
cxx_compiler_version:  # [linux]
  - 14.3.0             # [linux]
